'''
### Problem 0014 ### Longest Collatz sequence ###
Which starting number, under one million, produces the longest chain of terms in Collatz sequence?
'''


def Collatz_sequence(sequence):
    '''Recursive function. Return Collatz sequence as a list of consequitive numbers'''
    number = sequence[-1]
    if number == 1:
        return sequence
    elif number % 2 == 0:
        sequence.append(int(number/2)) 
    else:
        sequence.append(3*number + 1)
    return Collatz_sequence(sequence)



def solve_0014(startingNumber):
    maxSequence = { 'number' : int(startingNumber), 'sequenceLen' : 0 } 

    for number in range(int(startingNumber), 1, -1):        
        sequence = Collatz_sequence([number])        
        if len(sequence) > maxSequence['sequenceLen']:
            maxSequence['number'] = number
            maxSequence['sequenceLen'] = len(sequence)
        
        if startingNumber < 100:
            print('Numbers above {:0>3d} checked. Max sequence = {}'.format(number, maxSequence))            
        elif number%round(startingNumber/100, 0) == 0:
            print('Numbers above {:0>7d} checked. Max sequence = {}'.format(number, maxSequence))
    print('Longest Collatz sequence generated by starting number {} {}\n'.format(startingNumber, maxSequence))

solve_0014(13)
solve_0014(1e6)